### ISSUE TITLE
Tests with duplicate names

### ISSUE THREAD

**Issue by spiray** [CodingGarden/tdd-game-of-life#4]
https://github.com/CodingGarden/tdd-game-of-life/blob/b6d1eb7422c079f02c48146f9ffae40c37c1801f/test/Game.test.js#L103-L123
In the above code you have 2 tests with the same name. While watching the video i noticed that you didn't rename the test that you copied. I left a YouTube comment but i figured i would open an issue as well. Sorry i can't PR it now but i am not on my computer that is set up for programming. 
Thank You!

**Comment by w3cj** [comment]
Thanks for pointing that out! The tests both are testing the first column, but I could be more specific in the test description about which part of the first column they are testing. I'll update!
